/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.ControladorOT;
import static java.awt.SystemColor.control;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Ciudad;
import modelo.Pais;
import modelo.Paquete;
import modelo.PasoFronterizo;
import modelo.Prestador;
import modelo.Provincia;
import modelo.Rubro;
import modelo.Servicio;
import modelo.ServicioPaquete;
import modelo.ServicioPrestado;
import modelo.Tipo;

/**
 *
 * @author Rocío
 */
public class vistaModificarPaquete extends javax.swing.JFrame {
    private final ControladorOT control;

    /**
     * Creates new form vistaModificarPaquete
     */
    public vistaModificarPaquete(ControladorOT control) {
        initComponents();
        this.control = control;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoDias = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        campoItinerario = new javax.swing.JTextField();
        campoDescripcion = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        comboPais = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        campoNoches = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboProvincia = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        comboCiudad = new javax.swing.JComboBox();
        botonOrigen = new javax.swing.JButton();
        botonDestino = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDestinos = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        txtCC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        comboPaquetes = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        comboEstadoNuevo = new javax.swing.JComboBox();
        botonMP = new javax.swing.JButton();
        botonMostrar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtCupo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        comboRubro = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        botonAgregarSer = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        comboPrestador = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        comboServiciosPrestados = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaServicios = new javax.swing.JTable();
        txtDesde = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtHasta = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        comboServicio = new javax.swing.JComboBox();
        lblOrigen = new javax.swing.JLabel();
        botonQuitar = new javax.swing.JButton();
        botonQuitarServicio = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        comboPF = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(campoDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 60, -1));

        jLabel19.setText("Dias");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));
        getContentPane().add(campoItinerario, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 53, 192, 48));
        getContentPane().add(campoDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 53, 206, 48));

        jLabel18.setText("Itinerario");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 62, -1, -1));
        getContentPane().add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 58, 68, -1));

        jLabel2.setText("Descripcion");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 61, -1, -1));

        jLabel7.setText("Destinos");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, -1));

        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 61, -1, -1));

        comboPais.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboPais.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboPaisItemStateChanged(evt);
            }
        });
        comboPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPaisActionPerformed(evt);
            }
        });
        getContentPane().add(comboPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 117, -1));

        jLabel3.setText("Pais");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));
        getContentPane().add(campoNoches, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 68, -1));

        jLabel21.setText("Noches");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        jLabel4.setText("Provincia");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        comboProvincia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboProvincia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboProvinciaItemStateChanged(evt);
            }
        });
        getContentPane().add(comboProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 100, -1));

        jLabel5.setText("Ciudad");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, -1, -1));

        comboCiudad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 110, -1));

        botonOrigen.setText("Origen");
        botonOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOrigenActionPerformed(evt);
            }
        });
        getContentPane().add(botonOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 120, -1, -1));

        botonDestino.setText("Destino");
        botonDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDestinoActionPerformed(evt);
            }
        });
        getContentPane().add(botonDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 150, -1, -1));

        jLabel6.setText("Origen");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        tablaDestinos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaDestinos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 233, -1, 70));

        jLabel22.setText("Condiciones comerciales");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 60, -1, -1));

        txtCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCCActionPerformed(evt);
            }
        });
        getContentPane().add(txtCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 60, 90, -1));

        jLabel8.setText("Paquete");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 15, -1, -1));

        comboPaquetes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboPaquetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPaquetesActionPerformed(evt);
            }
        });
        getContentPane().add(comboPaquetes, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 12, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 791, 10));

        jLabel11.setText("Nuevo Estado");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 600, -1, -1));

        comboEstadoNuevo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activo", "Inactivo" }));
        getContentPane().add(comboEstadoNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 600, -1, -1));

        botonMP.setText("Modificar Paquete");
        botonMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMPActionPerformed(evt);
            }
        });
        getContentPane().add(botonMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 640, -1, -1));

        botonMostrar.setText("Mostrar");
        botonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(botonMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 11, -1, -1));

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, -1, -1));

        jLabel12.setText("Precio");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, -1, -1));
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 62, -1));

        jLabel13.setText("Cupo");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));
        getContentPane().add(txtCupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 62, -1));

        jLabel14.setText("Tipo");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, -1, -1));

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboTipoItemStateChanged(evt);
            }
        });
        getContentPane().add(comboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 110, -1));

        jLabel15.setText("Rubro");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        comboRubro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboRubro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboRubroItemStateChanged(evt);
            }
        });
        getContentPane().add(comboRubro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 827, -1));

        botonAgregarSer.setText("Agregar");
        botonAgregarSer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarSerActionPerformed(evt);
            }
        });
        getContentPane().add(botonAgregarSer, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 450, -1, -1));

        jLabel16.setText("Servicios");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, -1, -1));

        comboPrestador.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboPrestador.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboPrestadorItemStateChanged(evt);
            }
        });
        getContentPane().add(comboPrestador, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 410, 80, -1));

        jLabel17.setText("Servicios Prestados");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 410, -1, 20));

        comboServiciosPrestados.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboServiciosPrestados, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 410, -1, 20));

        jLabel20.setText("Desde");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, -1, -1));

        tablaServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaServicios);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, -1, 93));
        getContentPane().add(txtDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 62, -1));

        jLabel23.setText("Hasta");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, -1, -1));
        getContentPane().add(txtHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 63, -1));

        jLabel24.setText("Servicio");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 40, -1));

        jLabel25.setText("Prestador");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 80, -1));

        comboServicio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboServicioActionPerformed(evt);
            }
        });
        getContentPane().add(comboServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, -1, -1));

        lblOrigen.setText("origen");
        getContentPane().add(lblOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        botonQuitar.setText("Quitar");
        botonQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonQuitarActionPerformed(evt);
            }
        });
        getContentPane().add(botonQuitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, -1, -1));

        botonQuitarServicio.setText("Quitar");
        botonQuitarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonQuitarServicioActionPerformed(evt);
            }
        });
        getContentPane().add(botonQuitarServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 500, -1, -1));

        jLabel26.setText("Pasos Fronterizos");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 160, -1, -1));

        comboPF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 160, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboPaisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboPaisItemStateChanged
        if(comboPais.getSelectedIndex()>-1){
            control.ponerProvincias1(comboPais.getSelectedIndex());
        }
         if(comboPais.getSelectedIndex()>-1){
           control.ponerPF1(comboPais.getSelectedIndex());
       }
    }//GEN-LAST:event_comboPaisItemStateChanged

    private void comboProvinciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboProvinciaItemStateChanged
        if(comboProvincia.getSelectedIndex()>-1){
            control.ponerCiudades1(comboPais.getSelectedIndex(), comboProvincia.getSelectedIndex());
        }
    }//GEN-LAST:event_comboProvinciaItemStateChanged

    private void botonOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOrigenActionPerformed
       
    }//GEN-LAST:event_botonOrigenActionPerformed

    private void botonDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDestinoActionPerformed
        control.modificarCiudadDestino(comboPaquetes.getSelectedIndex(),comboPais.getSelectedIndex(),comboProvincia.getSelectedIndex(),comboCiudad.getSelectedIndex());
    }//GEN-LAST:event_botonDestinoActionPerformed

    private void comboPaquetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPaquetesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPaquetesActionPerformed

    private void botonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarActionPerformed
    control.mostrarPaquete(comboPaquetes.getSelectedIndex());
    }//GEN-LAST:event_botonMostrarActionPerformed

    private void comboTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboTipoItemStateChanged
        if(comboTipo.getSelectedIndex()>-1){
            control.ponerServicios1(comboRubro.getSelectedIndex(), comboTipo.getSelectedIndex());
        }
    }//GEN-LAST:event_comboTipoItemStateChanged

    private void comboRubroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboRubroItemStateChanged
        if(comboRubro.getSelectedIndex()>-1){
             control.ponerTipos1(comboRubro.getSelectedIndex());
        }
    }//GEN-LAST:event_comboRubroItemStateChanged

    private void botonAgregarSerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarSerActionPerformed
        control.agregarServicio();
    }//GEN-LAST:event_botonAgregarSerActionPerformed

    private void botonQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonQuitarActionPerformed
       control.quitarDestino(comboPaquetes.getSelectedIndex(),tablaDestinos.getSelectedRow());
    }//GEN-LAST:event_botonQuitarActionPerformed

    private void comboPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPaisActionPerformed

    public String getNombre(){
        return campoNombre.getText();
    }
    
    public String getDescripcion(){
        return campoDescripcion.getText();
    }
    
    public String getItinerario(){
        return campoItinerario.getText();
    }
    
    public int getDias(){
        return Integer.parseInt(campoDias.getText());
    }
    
    public int getNoches(){
        return Integer.parseInt(campoNoches.getText());
    }
    
    public String getCC(){
        return txtCC.getText();
    }
    
    
    public int getEstadoIndex(){
        
        return comboEstadoNuevo.getSelectedIndex();
    }
    
    private void botonMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMPActionPerformed
        control.modificarPaquete(comboPaquetes.getSelectedIndex(),comboPais.getSelectedIndex(),comboProvincia.getSelectedIndex(),comboCiudad.getSelectedIndex());
        JOptionPane.showMessageDialog(this, "Paquete modificado, presione salir para volver al menu");
    }//GEN-LAST:event_botonMPActionPerformed

    private void botonQuitarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonQuitarServicioActionPerformed
      control.quitarServicio(comboPaquetes.getSelectedIndex(),tablaServicios.getSelectedRow());
    }//GEN-LAST:event_botonQuitarServicioActionPerformed

    private void comboServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboServicioActionPerformed

    private void txtCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCCActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        control.salirMP();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void comboPrestadorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboPrestadorItemStateChanged
       if(comboPrestador.getSelectedIndex()>-1){
           control.ponerServiciosPrestados1(comboPrestador.getSelectedIndex());
       }
    }//GEN-LAST:event_comboPrestadorItemStateChanged

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarSer;
    private javax.swing.JButton botonDestino;
    private javax.swing.JButton botonMP;
    private javax.swing.JButton botonMostrar;
    private javax.swing.JButton botonOrigen;
    private javax.swing.JButton botonQuitar;
    private javax.swing.JButton botonQuitarServicio;
    private javax.swing.JButton botonSalir;
    private javax.swing.JTextField campoDescripcion;
    private javax.swing.JTextField campoDias;
    private javax.swing.JTextField campoItinerario;
    private javax.swing.JTextField campoNoches;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JComboBox comboCiudad;
    private javax.swing.JComboBox comboEstadoNuevo;
    private javax.swing.JComboBox comboPF;
    private javax.swing.JComboBox comboPais;
    private javax.swing.JComboBox comboPaquetes;
    private javax.swing.JComboBox comboPrestador;
    private javax.swing.JComboBox comboProvincia;
    private javax.swing.JComboBox comboRubro;
    private javax.swing.JComboBox comboServicio;
    private javax.swing.JComboBox comboServiciosPrestados;
    private javax.swing.JComboBox comboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblOrigen;
    private javax.swing.JTable tablaDestinos;
    private javax.swing.JTable tablaServicios;
    private javax.swing.JTextField txtCC;
    private javax.swing.JTextField txtCupo;
    private javax.swing.JTextField txtDesde;
    private javax.swing.JTextField txtHasta;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables

public void ponerPaquetes(ArrayList<Paquete> paquetes) {
      comboPaquetes.removeAllItems();
      for(Paquete p : paquetes){
          comboPaquetes.addItem(p.getNombre());
      }
    }

    public void setNombre(String nombre) {
       campoNombre.setText(nombre);
    }

    public void setDescripcion(String descripcion) {
       campoDescripcion.setText(descripcion);
    }

    public void setItinerario(String itinerario) {
        campoItinerario.setText(itinerario);
    }

    public void setDias(int dias) {
        campoDias.setText(String.valueOf(dias));
    }

    public void setNoches(int noches) {
        campoNoches.setText(String.valueOf(noches));
    }

    public void setCondicionesComerciales(String condComerciales) {
        txtCC.setText(condComerciales);
    }

    public void setOrigen(String nombre) {
        lblOrigen.setText(nombre);
    }

    public void mostrarDestinos(ArrayList<Ciudad> destinos) {
       DefaultTableModel matriz = new DefaultTableModel();
       matriz.addColumn("Pais");
       matriz.addColumn("Provincia");
       matriz.addColumn("Ciudad");
       for(Ciudad c : destinos){
           matriz.addRow(new Object[]{
               c.getProvincia().getPais().getNombre(),
               c.getProvincia().getNombre(),
               c.getNombre()
           });
       }
       tablaDestinos.setModel(matriz);
    }

    public void mostrarServicios(ArrayList<ServicioPaquete> serviciosPaq) {
      DefaultTableModel matriz = new DefaultTableModel();
        matriz.addColumn("Rubro");
        matriz.addColumn("Tipo");
        matriz.addColumn("Servicio");
        matriz.addColumn("Desde");
        matriz.addColumn("Hasta");
        matriz.addColumn("Cupo");
        matriz.addColumn("Precio");
        matriz.addColumn("Servicio Prestado");
        matriz.addColumn("Prestador");
        for(ServicioPaquete s : serviciosPaq){
            matriz.addRow(new Object[]{
                s.getServicio().getTipo().getRubro().getDescripcion(),
                s.getServicio().getTipo().getDescripcion(),
                s.getServicio().getDescripcion(),
                s.getDesde(),
                s.getHasta(),
                s.getServicioSalida().getCupo(),
                s.getServicioSalida().getPrecio(),
                s.getServicioSalida().getServicioPrestado().getNombre(),
                s.getServicioSalida().getServicioPrestado().getPrestador().getRazonSocial(),
            });
        }
        tablaServicios.setModel(matriz);  
    }

 public void ponerPaises(ArrayList<Pais> paises) {
        comboPais.removeAllItems();
        for (Pais p : paises){
            comboPais.addItem(p.getNombre());
        }
        comboPais.setSelectedIndex(0);
       // ponerProvincias();
    }

    public void ponerProvincias(ArrayList<Provincia> provincias) {
       comboProvincia.removeAllItems();
        for (Provincia p : provincias){
            comboProvincia.addItem(p.getNombre());
        }
        comboProvincia.setSelectedIndex(0);
    }

    public void ponerCiudades(ArrayList<Ciudad> ciudades) {
        comboCiudad.removeAllItems();
       for (Ciudad c : ciudades){
           comboCiudad.addItem(c.getNombre());
       }
    }

    public void ponerOrigen(String nombre) {
      lblOrigen.setText(nombre);
    }

    public void ponerPF(ArrayList<PasoFronterizo> pasosFronterizos) {
      comboPF.removeAllItems();
        for(PasoFronterizo pf : pasosFronterizos){
            comboPF.addItem(pf.getNombre());
        }
    }

    public void ponerRubros(ArrayList<Rubro> rubros) {
        comboRubro.removeAllItems();
        for(Rubro r : rubros){
            comboRubro.addItem(r.getDescripcion());        
        }
    }

    public void ponerTipos(ArrayList<Tipo> tipos) {
        comboTipo.removeAllItems();
        for(Tipo t : tipos){
            comboTipo.addItem(t.getDescripcion());
        }

    }

    public void ponerServicios(ArrayList<Servicio> servicios) {
        comboServicio.removeAllItems();
        for(Servicio s : servicios){
            comboServicio.addItem(s.getDescripcion());
        }

    }

    public void ponerPrestadores(ArrayList<Prestador> prestadores) {
        comboPrestador.removeAllItems();
        for(Prestador p : prestadores){
            comboPrestador.addItem(p.getRazonSocial());  
        }
    }

    public void ponerServiciosPrestados(ArrayList<ServicioPrestado> serviciosPrestados) {
        comboServiciosPrestados.removeAllItems();
        for(ServicioPrestado sp : serviciosPrestados){
            comboServiciosPrestados.addItem(sp.getNombre());
        }
    }    
}