/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.ControladorOT;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Base;
import modelo.EstadoSalida;
import modelo.Paquete;
import modelo.Salida;
import modelo.Tarifa;

/**
 *
 * @author Rocío
 */
public class vistaSalida extends javax.swing.JFrame {
    private final ControladorOT control;

    /**
     * Creates new form vistaSalida
     */
    public vistaSalida(ControladorOT control) {
        initComponents();
        this.control = control;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        comboPaquete = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSalidasdePaquete = new javax.swing.JTable();
        botonAgregarSalida = new javax.swing.JButton();
        comboFS = new org.jdesktop.swingx.JXDatePicker();
        comboFR = new org.jdesktop.swingx.JXDatePicker();
        jLabel6 = new javax.swing.JLabel();
        txtCupo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        comboBases = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtTarifa = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaTarifas = new javax.swing.JTable();
        botonSalir = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crear Salida");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Paquete");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 36, -1, -1));
        getContentPane().add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 33, 72, -1));

        comboPaquete.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboPaquete.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboPaqueteItemStateChanged(evt);
            }
        });
        comboPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPaqueteActionPerformed(evt);
            }
        });
        getContentPane().add(comboPaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 33, -1, -1));

        jLabel2.setText("Numero");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 36, -1, -1));

        jLabel3.setText("Fecha Salida");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 36, -1, -1));

        jLabel4.setText("Fecha Regreso");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, -1, -1));

        jLabel5.setText("Salidas existentes");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        tablaSalidasdePaquete.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaSalidasdePaquete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaSalidasdePaqueteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaSalidasdePaquete);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 249, 106));

        botonAgregarSalida.setText("Agregar salida");
        botonAgregarSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(botonAgregarSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        comboFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFSActionPerformed(evt);
            }
        });
        getContentPane().add(comboFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));
        getContentPane().add(comboFR, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, -1, -1));

        jLabel6.setText("Cupo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 70, -1, -1));
        getContentPane().add(txtCupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 67, 81, -1));

        jLabel7.setText("Base");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        comboBases.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboBases, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        jLabel8.setText("Tarifa");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));
        getContentPane().add(txtTarifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 69, -1));

        jButton1.setText("Agregar tarifa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, -1, -1));

        jLabel9.setText("Tarifas");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, -1, -1));

        tablaTarifas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaTarifas);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 249, 106));

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPaqueteActionPerformed
        
    }//GEN-LAST:event_comboPaqueteActionPerformed

    private void comboPaqueteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboPaqueteItemStateChanged
     if(comboPaquete.getSelectedIndex()> -1){
         control.mostrarSalidas(comboPaquete.getSelectedIndex());
     }
    }//GEN-LAST:event_comboPaqueteItemStateChanged

    private void comboFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboFSActionPerformed
    public int getNumero(){
        return Integer.parseInt(txtNumero.getText());
    }
    
    public Date getFS(){
        return comboFS.getDate();        
    }
    
    public Date getFR(){
        return comboFR.getDate();
    }
    
    public int getCupo(){
        return Integer.parseInt(txtCupo.getText());
    }
    private void botonAgregarSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarSalidaActionPerformed
    control.agregarSalida(comboPaquete.getSelectedIndex()); 
    }//GEN-LAST:event_botonAgregarSalidaActionPerformed

    private void tablaSalidasdePaqueteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaSalidasdePaqueteMouseClicked
       control.mostrarTarifas(comboPaquete.getSelectedIndex(),tablaSalidasdePaquete.getSelectedRow());
    }//GEN-LAST:event_tablaSalidasdePaqueteMouseClicked
    public float getPrecio(){
        return Float.parseFloat(txtTarifa.getText());
    }
    public int getBaseIndex(){
        return comboBases.getSelectedIndex();
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      if(tablaSalidasdePaquete.getSelectedRow()>-1){
          control.agregarTarifa(comboPaquete.getSelectedIndex(),tablaSalidasdePaquete.getSelectedRow());
          control.mostrarTarifas(comboPaquete.getSelectedIndex(), tablaSalidasdePaquete.getSelectedRow());
          txtTarifa.setText("");
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        control.salirSalida();
    }//GEN-LAST:event_botonSalirActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarSalida;
    private javax.swing.JButton botonSalir;
    private javax.swing.JComboBox comboBases;
    private org.jdesktop.swingx.JXDatePicker comboFR;
    private org.jdesktop.swingx.JXDatePicker comboFS;
    private javax.swing.JComboBox comboPaquete;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tablaSalidasdePaquete;
    private javax.swing.JTable tablaTarifas;
    private javax.swing.JTextField txtCupo;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtTarifa;
    // End of variables declaration//GEN-END:variables

    public void ponerPaquetes(ArrayList<Paquete> paquetes) {
      comboPaquete.removeAllItems();
      for(Paquete p : paquetes){
          comboPaquete.addItem(p.getNombre());
      }
    }

    public void mostrarSalidas(ArrayList<Salida> salidas) {
       DefaultTableModel matriz = new DefaultTableModel();
       matriz.addColumn("Cupo");
       matriz.addColumn("Fecha Inicio");
       matriz.addColumn("Fecha Regreso");
       matriz.addColumn("Numero de Salida");
       matriz.addColumn("Estado");
    for(Salida s : salidas){
    //if(s.getEstadoSalida()==EstadoSalida.EnPausa){
        matriz.addRow(new Object[]{
        s.getCupo(),
        s.getFechaInicio(),
        s.getFechaFin(),
        s.getNumero(),
        s.getEstadoSalida()
    });
    //}
    }
    tablaSalidasdePaquete.setModel(matriz);
}

    public void ponerBases(ArrayList<Base> bases) {
       comboBases.removeAllItems();
       for(Base b : bases){
           comboBases.addItem(b.getTipo());
       }
    }

    public void ponerBasesTabla(Salida s) {
       DefaultTableModel matriz = new DefaultTableModel();
       matriz.addColumn("Base");
       matriz.addColumn("Precio");
       for(Tarifa t : s.getTarifas()){
           matriz.addRow(new Object[]{
               t.getBase().getTipo(),
               t.getPrecio()
           });
       }
       tablaTarifas.setModel(matriz);
    }
}
