/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.ControladorOT;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.*;


/**
 *
 * @author Rocío
 */
public class vistaModificarSalida extends javax.swing.JFrame {
 private final ControladorOT control;
    /**
     * Creates new form vistaModificarSalida
     */
    public vistaModificarSalida(ControladorOT control) {
        initComponents();
        this.control = control;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        comboFR = new org.jdesktop.swingx.JXDatePicker();
        botonModificarSalida = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboPaquete = new javax.swing.JComboBox();
        txtCupo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboFS = new org.jdesktop.swingx.JXDatePicker();
        jLabel5 = new javax.swing.JLabel();
        comboSalidas = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        comboBases = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtTarifa = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaTarifas = new javax.swing.JTable();
        botonQuitarServicio = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modificar Salida");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Cupo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));
        getContentPane().add(comboFR, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        botonModificarSalida.setText("Modificar Salida");
        botonModificarSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(botonModificarSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, -1));

        jLabel1.setText("Paquete");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 48, -1, -1));

        jLabel3.setText("Fecha Salida");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        comboPaquete.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboPaquete.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboPaqueteItemStateChanged(evt);
            }
        });
        comboPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPaqueteActionPerformed(evt);
            }
        });
        getContentPane().add(comboPaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 45, 81, -1));
        getContentPane().add(txtCupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 81, -1));

        jLabel4.setText("Fecha Regreso");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        comboFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFSActionPerformed(evt);
            }
        });
        getContentPane().add(comboFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel5.setText("Salida");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 48, -1, -1));

        comboSalidas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboSalidas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboSalidasItemStateChanged(evt);
            }
        });
        getContentPane().add(comboSalidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 45, 81, -1));

        jLabel7.setText("Base");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        comboBases.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboBases, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        jLabel8.setText("Tarifa");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));
        getContentPane().add(txtTarifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 70, -1));

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        tablaTarifas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaTarifas);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 249, 106));

        botonQuitarServicio.setText("Quitar");
        botonQuitarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonQuitarServicioActionPerformed(evt);
            }
        });
        getContentPane().add(botonQuitarServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, -1));

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
        public Date getFS(){
        return comboFS.getDate();        
    }
    
    public Date getFR(){
        return comboFR.getDate();
    }
    
    public int getCupo(){
        return Integer.parseInt(txtCupo.getText());
    }
    
        public float getPrecio(){
        return Float.parseFloat(txtTarifa.getText());
    }
    public int getBaseIndex(){
        return comboBases.getSelectedIndex();
    }
    
    private void botonModificarSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarSalidaActionPerformed
          control.modificarSalida(comboPaquete.getSelectedIndex(), comboSalidas.getSelectedIndex());
          JOptionPane.showMessageDialog(this, "Salida, presione salir para volver al menu");
    }//GEN-LAST:event_botonModificarSalidaActionPerformed

    private void comboPaqueteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboPaqueteItemStateChanged
        if(comboPaquete.getSelectedIndex()> -1){
            control.ponerSalidas(comboPaquete.getSelectedIndex());
        }
    }//GEN-LAST:event_comboPaqueteItemStateChanged

    private void comboPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPaqueteActionPerformed

    }//GEN-LAST:event_comboPaqueteActionPerformed

    private void comboFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboFSActionPerformed

    private void comboSalidasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboSalidasItemStateChanged
        
    }//GEN-LAST:event_comboSalidasItemStateChanged

    private void botonQuitarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonQuitarServicioActionPerformed
        control.quitarTarifa(comboPaquete.getSelectedIndex(), comboSalidas.getSelectedIndex(), tablaTarifas.getSelectedRow());
    }//GEN-LAST:event_botonQuitarServicioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:control.agregarTarifa(comboPaquete.getSelectedIndex(),tablaSalidasdePaquete.getSelectedRow());
    control.mostrarTarifasMod(comboPaquete.getSelectedIndex(), comboSalidas.getSelectedIndex());
    txtTarifa.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        control.salirMS();
    }//GEN-LAST:event_botonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonModificarSalida;
    private javax.swing.JButton botonQuitarServicio;
    private javax.swing.JButton botonSalir;
    private javax.swing.JComboBox comboBases;
    private org.jdesktop.swingx.JXDatePicker comboFR;
    private org.jdesktop.swingx.JXDatePicker comboFS;
    private javax.swing.JComboBox comboPaquete;
    private javax.swing.JComboBox comboSalidas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tablaTarifas;
    private javax.swing.JTextField txtCupo;
    private javax.swing.JTextField txtTarifa;
    // End of variables declaration//GEN-END:variables

    public void ponerPaquetes(ArrayList<Paquete> paquetes) {
       comboPaquete.removeAllItems();
      for(Paquete p : paquetes){
          comboPaquete.addItem(p.getNombre());
      }
    }

    public void ponerSalidas(ArrayList<Salida> salidas) {
       comboSalidas.removeAllItems();
       for(Salida s : salidas){
                   if(s.getEstadoSalida()==EstadoSalida.EnPausa){
           comboSalidas.addItem(s);
       }
       }     
    }

    public void ponerBasesTabla(Salida s) {
       DefaultTableModel matriz = new DefaultTableModel();
       matriz.addColumn("Base");
       matriz.addColumn("Precio");
       for(Tarifa t : s.getTarifas()){
           matriz.addRow(new Object[]{
               t.getBase().getTipo(),
               t.getPrecio()
           });
       }
       tablaTarifas.setModel(matriz);
    }
 
}
